version: 1.2.{build}
skip_tags: true
image: Visual Studio 2017
configuration: Release
platform: Any CPU

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  
branches:
  only:
    - master
    - release
    - /^(.*\/)?ci-.*$/
    
before_build:
  - appveyor-retry dotnet restore -v Minimal
  
build_script:
  - dotnet build ./ServiceBase.sln -c Release /property:Version=%APPVEYOR_BUILD_VERSION%
  
after_build:
  - nuget pack ./src/ServiceBase/ServiceBase.nuspec -OutputDirectory ./artifacts/packages -version %APPVEYOR_BUILD_VERSION%
  - nuget pack ./src/ServiceBase.Mvc/ServiceBase.Mvc.nuspec -OutputDirectory ./artifacts/packages -version %APPVEYOR_BUILD_VERSION%
  - nuget pack ./src/ServiceBase.Events.RabbitMQ/ServiceBase.Events.RabbitMQ.nuspec -OutputDirectory ./artifacts/packages -version %APPVEYOR_BUILD_VERSION%
  - nuget pack ./src/ServiceBase.Notification.SendGrid/ServiceBase.Notification.SendGrid.nuspec -OutputDirectory ./artifacts/packages -version %APPVEYOR_BUILD_VERSION%
  - nuget pack ./src/ServiceBase.Notification.Smtp/ServiceBase.Notification.Smtp.nuspec -OutputDirectory ./artifacts/packages -version %APPVEYOR_BUILD_VERSION%
  - nuget pack ./src/ServiceBase.Notification.Twilio/ServiceBase.Notification.Twilio.nuspec -OutputDirectory ./artifacts/packages -version %APPVEYOR_BUILD_VERSION%

test_script:
  - bash coveralls.sh
  
artifacts:
  - path: artifacts\**\*.*
  
cache:
  - '%USERPROFILE%\.nuget\packages'