name: .NET

on:
  push:
    branches: [ net5 ]
  pull_request:
    branches: [ net5 ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Set version number
      run: |
        $version = "3.2."+(4000+$($Env:GITHUB_RUN_NUMBER))+".0"
        echo $version
        echo "VERSION_NUMBER=$version" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append

    - name: Output Run Number
      run: echo ${{ github.run_number }}




    #- name: Restore dependencies
    #  run: dotnet restore

    #- name: Build
    #  run: dotnet build --no-restore --configuration Release

    #- name: Test
    #  run: dotnet test --no-build --verbosity normal --configuration Release
