name: .NET

on:
  push:
    branches: [ net5 ]
  pull_request:
    branches: [ net5 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage";
      
    - name: ReportGenerator
      uses: danielpalme/ReportGenerator-GitHub-Action@5.0.2
      with:
        reports: './test/ServiceBase.UnitTests/TestResults/*/coverage.cobertura.xml'
        targetdir: 'coveragereport' 
    
    - name: Upload coverage report artifact
      uses: actions/upload-artifact@v2.2.3
      with:
        name: CoverageReport     
        path: coveragereport
